addSbtPlugin("com.github.sbt"            % "sbt-dynver"          % "5.1.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.11.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.14.2")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.10.0")
