addSbtPlugin("com.dwijnand"              % "sbt-dynver"          % "4.0.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.3.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.10")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.6.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.11")
